slugnotes/study_notes_project/study_notes_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from user_profile import views as user_profile
from landing import views as landing
from flash_cards import views as flash_cards
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
	
	url(r'^$', landing.Home),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', user_profile.Login),
    url(r'^accounts/logout/$', user_profile.Logout),
    url(r'^accounts/signup/$', user_profile.Signup),
    url(r'^accounts/profile/$', user_profile.Profile),
    url(r'^accounts/change_password/$', user_profile.Change_Password),
    url(r'^accounts/reset/password_reset/$', password_reset, name='reset_password_reset1'),
    url(r'^accounts/password_reset/done/$', password_reset_done, name='password_reset_done'),
    url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, name='password_reset_confirm'),
    url(r'^accounts/reset/done/$', password_reset_complete, name='password_reset_complete'),
    url(r'^cards/new_deck/$', flash_cards.New_Deck),
    url(r'^cards/upload_file/$', flash_cards.Upload_File),
    url(r'^cards/clone/$', flash_cards.Clone),
    url(r'^cards/edit_deck/$', flash_cards.Edit_Deck),
    url(r'^cards/delete_deck/$', flash_cards.Delete_Deck),
    url(r'^cards/new_card/$', flash_cards.New_Card),
    url(r'^cards/edit_card/$', flash_cards.Edit_Card),
    url(r'^cards/delete_card/$', flash_cards.Delete_Card),
    url(r'^cards/search/$', flash_cards.Search),
    url(r'^cards/view_shared_deck/$', flash_cards.View_Shared_Deck),
    url(r'^cards/shared_decks/$', flash_cards.Shared_Decks),
    url(r'^cards/study/$',flash_cards.Study),
    url(r'^cards/', flash_cards.View_Deck),
    
]

slugnotes/study_notes_project/flash_cards/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# fix the default value for deck_name
# don't allow the user to edit things they shouldn't use
SHARE_CHOICES = [(0,"No"), (1,"Yes")]
class Deck(models.Model):
	deck_id = models.AutoField(primary_key=True, editable=False)
	user = models.ForeignKey(User)
	deck_name = models.CharField(max_length=20, blank=False)
	share_flag = models.BooleanField(choices=SHARE_CHOICES, default=0)
	date_created = models.DateTimeField(auto_now_add=True, editable=False)
	date_modified = models.DateTimeField(auto_now=True, editable=False)
	deleted_flag = models.BooleanField(default=0, editable=False)

class Card(models.Model):
	card_id = models.AutoField(primary_key=True, editable=False)
	deck = models.ForeignKey(Deck)
	front = models.CharField(max_length=1000)
	back = models.CharField(max_length=2000)
	date_created = models.DateTimeField(auto_now_add=True, editable=False)
	date_modified = models.DateTimeField(auto_now=True, editable=False)
	deleted_flag = models.BooleanField(default=0, editable=False)

slugnotes/study_notes_project/flash_cards/forms.py
from django import forms
from .models import Deck, Card

class NewDeck(forms.ModelForm):

	#deck_name = forms.CharField(required=True)

	class Meta:
		model = Deck
		fields = ("user", "deck_name", "share_flag")
		labels = {
			'share_flag' : 'Share With Others'
		}
		widgets = {'user': forms.HiddenInput()}


	def clean_deck_name(self):
		user_id = self.cleaned_data['user']
		deck_name = self.cleaned_data['deck_name']
		total = None
	
		total = Deck.objects.filter(deck_name=deck_name, user_id=user_id, deleted_flag = 0)
		if not total:
			return deck_name
		if "deck_name" in self.changed_data:
			raise forms.ValidationError('You already have a deck with that name.')

class NewCard(forms.ModelForm):

	front = forms.CharField( required=True, max_length=1000, label="Front of Card", widget=forms.Textarea(attrs={'class':"form-control"}) )
	back = forms.CharField( required=False, max_length=2000, label="Back of Card", widget=forms.Textarea(attrs={'class':"form-control"}) )

	class Meta:
		model = Card
		fields = ("front", "back", "deck")
		widgets = {'deck': forms.HiddenInput()}

class UploadFile(forms.Form):
    file = forms.FileField(required=False)
    text = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows':13, 'cols':33}))
    deck_id = forms.CharField(widget = forms.HiddenInput())

    def clean(self):

        # Get the field values submitted
        cleaned_data = super(UploadFile, self).clean()
        file = cleaned_data.get('file')
        text = cleaned_data.get('text')
        if file == None and text == "":
			raise forms.ValidationError('Please fill out a field.')

        if file and text:
            raise forms.ValidationError('Only fill out one field please.', code='invalid')

        if file:
        	try:
	        	file, extension = str(file).split('.')
	        except ValueError:
	        	raise forms.ValidationError('The file has no extension, please use a .txt file')
	        if extension != 'txt':
	        	raise forms.ValidationError('Please select a .txt file')

slugnotes/study_notes_project/flash_cards/views.py
from django.shortcuts import render
from flash_cards.forms import NewDeck, UploadFile, NewCard
from django.http import HttpResponse, HttpResponseRedirect
import json
from flash_cards.models import Card, Deck
from django.core.signing import Signer
from django.core import signing
from django.shortcuts import get_object_or_404
from parse_notes import parse_notes
import re
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models import Q

def New_Deck(request):
	if request.method == 'POST':
		user = request.POST.get('user')
		deck_name = request.POST.get('deck_name')
		share_flag = request.POST.get('share_flag')
		if share_flag == 'false':
			share_flag = 0
		else:
			share_flag = 1
		data = {'user' : user, 'deck_name' : deck_name, 'share_flag' : share_flag}
		
		form = NewDeck(data)
		if form.is_valid():
			print "valid form"
			deck = form.save(commit=False)
			deck.user_id = user
			deck.save()
		else:
			print "error"
			errors = form.errors
			print errors
			return HttpResponse(json.dumps(errors))

	return HttpResponse(json.dumps({"success": "success"}))

def Edit_Deck(request):
    if request.method == 'POST':
        deck_id_signed = request.POST.get('deck_id')
        deck_id = None
        signer = Signer(request.user.id)
        try:
        	deck_id = signer.unsign(deck_id_signed)
        except signing.BadSignature:
    		print("Tampering detected!!")
    		return HttpResponseRedirect('/')
        deck_name = request.POST.get('deck_name')
        user = request.POST.get('user')
        share_flag = request.POST.get('share_flag')
        if share_flag == 'false':
            share_flag = 0
        else:
            share_flag = 1
        data = {'user' : user, 'deck_name' : deck_name, "share_flag" : share_flag}
        deck = get_object_or_404(Deck, deck_id=deck_id)
        if deck.deck_name == deck_name:
            deck.share_flag = share_flag
            deck.save()
        else:
            form = NewDeck(data)
            if form.is_valid():

                #deck = get_object_or_404(Deck, deck_id=deck_id)
                deck.deck_name = deck_name
                deck.share_flag = share_flag
                deck.save()
            else:
                errors = form.errors
                return HttpResponse(json.dumps(errors))
    
    return HttpResponse(json.dumps({"success": "success"}))

def Delete_Deck(request):
    deck_id_signed = request.POST.get('deck')
    deck_id = None
    signer = Signer(request.user.id)
    try:
        deck_id = signer.unsign(deck_id_signed)
    except signing.BadSignature:
        print("Tampering detected! Delete deck")
        return HttpResponse(json.dumps(errors))
    deck = get_object_or_404(Deck, deck_id=deck_id)
    deck.deleted_flag = 1
    deck.save()
    return HttpResponse(json.dumps({"success": "success"}))

def Upload_File(request):
    if request.method == 'POST':
        deck_id = request.POST.get('deck_id')
        signer = Signer(request.user.id)
        try:
            deck_id = signer.unsign(deck_id)
        except signing.BadSignature:
            return HttpResponse(json.dumps({"error": "error"}))
        form = UploadFile(request.POST, request.FILES)
        if form.is_valid():
            content = None
            if request.POST.get('text', False) != False:
                content = request.POST['text']
            if request.FILES.get('file', False) != False:
                print request.FILES['file']
                content = request.FILES['file']
                content = content.read()
            cardslist = parse_notes(content)
            #check that there are any cards to create
            if cardslist:
                front = None
                back = ""
                #loop through card list and generate a new card for the deck
                for card in reversed(cardslist):
                    if len(card) > 1:
                        front = card.pop(0)
                        for line in card:
                            print line
                            back += re.sub(r'\r', '', line) + "\n"
                    else:
                        front = card.pop(0)
                    new_card = Card.objects.create(deck_id = deck_id, front=front,back=back)
                    back = ""
        else:
            print "error in Upload File"
            errors = form.errors
            print errors
            print json.dumps(errors)
            return HttpResponse(json.dumps(errors))
    return HttpResponse(json.dumps({"success": "success"}))

def View_Deck(request):
    deck_id_signed = request.GET.get('deck_id')
    deck_id = None
    card_list =[]
    signer = Signer(request.user.id)
    try:
        deck_id = signer.unsign(deck_id_signed)
    except signing.BadSignature:
        print("Tampering detected! View deck")
        return HttpResponseRedirect('/')
    form = NewCard(initial={'deck' : request.GET.get('deck_id')})
    cards = Card.objects.filter(deck_id=deck_id, deleted_flag = 0).order_by('-date_created')
    deck = Deck.objects.filter(deck_id=deck_id, deleted_flag = 0)
    print "here"
    deck_name = ""
    try:
        deck_name = deck[0].deck_name
    except IndexError:
        deck_name = ""
    for card in cards:
        card_list.append({
            "card_id" : card.card_id,
            "front" : card.front,
            "back" : card.back,
            }) 
    upload_form = UploadFile(initial={"deck_id" : signer.sign(deck_id)})
    context = {
        "upload_form" : upload_form,
        "form" : form,
        "card_list" : card_list,
        "deck_id" : deck_id_signed,
        "deck_name" : deck_name, 
    }
    return render(request, 'flash_cards/view_deck.html', context)


def New_Card(request):
    if request.method == 'POST':
        deck = request.POST.get('deck')
        front = request.POST.get('front')
        back = request.POST.get('back')
        signer = Signer(request.user.id)
        try:
            deck = signer.unsign(deck)
        except signing.BadSignature:
            return HttpResponseRedirect('/')
        data = {'deck' : deck, 'front' : front, 'back' : back}	
        form = NewCard(data)
        if form.is_valid():
            print "valid form"
            card = form.save(commit=False)
            card.deck_id = deck
            card.save()
        else:
            print "error"
            errors = form.errors
            print errors
            return HttpResponse(json.dumps(errors))

    return HttpResponse(json.dumps({"success": "success"}))

def Edit_Card(request):
        if request.method == 'POST':
                id_card = request.POST.get('card')
		deck = request.POST.get('deck')
		front = request.POST.get('front')
		back = request.POST.get('back')
		signer = Signer(request.user.id)
		try:
			deck = signer.unsign(deck)
		except signing.BadSignature:
			return HttpResponseRedirect('/')
		data = {'deck' : deck, 'front' : front, 'back' : back}		
		form = NewCard(data)
                if form.is_valid():
                        card = get_object_or_404(Card, card_id=id_card)
                        card.front = front
                        card.back = back
                        card.save()
                else:
                        errors = form.errors
                        return HttpResponse(json.dumps(errors))
        
        return HttpResponse(json.dumps({"success": "success"}))

def Delete_Card(request):
        card_id = request.POST.get('card')
        deck_id_signed = request.POST.get('deck')
        deck_id = None
	signer = Signer(request.user.id)
	try:
                deck = signer.unsign(deck_id_signed)
	except signing.BadSignature:
		print("Tampering detected! Delete card")
		return HttpResponse(json.dumps(errors))
        card = get_object_or_404(Card, card_id=card_id)
        card.deleted_flag = 1
        card.save()
	return HttpResponse(json.dumps({"success": "success"}))

@login_required
def Search(request):
    query = request.GET.get('query')
    users = User.objects.filter(username__contains=str(query))
    user_list = []
    signer = Signer(request.user.id)
    #SQL SELECT * FROM flash_cards_deck where deck_name like '%hello%' and deleted_flag = 0 and share_flag = 1
    decks = Deck.objects.filter(deck_name__contains=str(query), share_flag = 1, deleted_flag = 0).exclude(user_id=request.user.id)
    deck_list = []
    for user in users:
        public_deck_count = Deck.objects.filter(user_id = user.id, share_flag = 1).count()
        user_list.append({
            "user" : user.id,
            "signed_user" : signer.sign(user.id),
            "username" : user.username,
            "public_deck_count" : public_deck_count,
            })
    for deck in decks:
        username = ""
        
        user = User.objects.filter(id = deck.user_id)
        card_count = Card.objects.filter(deck_id = deck.deck_id, deleted_flag = 0).count()
        try:
            username = user[0].username
        except IndexError:
            username = ""
        deck_list.append({
            "orig_deck_id" : signer.sign(deck.deck_id),
            "deck_name" : deck.deck_name,
            "share" : deck.share_flag,
            "username" : username,
            "card_count" : card_count
            })
    form = NewDeck(initial={'user' : request.user.id})
    context = {
        "user_list" : user_list,
        "deck_list" : deck_list,
        "clone_form" : form,
        "sign" : signer.sign(request.user.id),
        "query" : query,
    }
    return render(request, 'flash_cards/search.html', context)

def Shared_Decks(request):
    u_id = request.GET.get('u_id')
    user = None
    user_name = None
    signer = Signer(request.user.id)
    try:
        user = signer.unsign(u_id)
    except signing.BadSignature:
        return HttpResponse(json.dumps({"Tampering": "bad signature"}))
    shared_decks = Deck.objects.filter(user_id = user, share_flag = 1, deleted_flag = 0)

slugnotes/study_notes_project/templates/flash_cards/search.html
{% extends "base.html" %}
{% block content %}

<!-- Title -->
<div class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-sm-4">
        <h3>Search Results for: {{ query }} </h3>
      </div>
    </div>
  </div>
</div>
<!-- End Title -->

<!-- Search Results Container-->
<div class="container">

  <!-- User Results: only show users that have public decks -->
  <div class="user_search_results">
  <h1>Users:</h1> 
    {% if user_list %}
      <div class="row mar-b-30">
        <div class="col-md-12">
          {% for user in user_list %}
          {% if user.public_deck_count > 0 %}
            <div id="user_{{user.user}}" class="UserResult">
              <div class="image-caption image-caption-search-result">
                <a href="/cards/shared_decks/?u_id={{ user.signed_user }}" class="user_result_options label label-info icon" data-toggle="tooltip" data-placement="top" title="View">
                  <i class="deck_options fa fa-eye"></i>
                </a>
              </div>
              <div class="User icon-wrap ico-bg round-five {% cycle 'user_color1' 'user_color2' 'user_color3' %}">
                <i class="fa fa-smile-o"></i>
              </div>
              <h4>{{ user.username }}</h4>
              <h5>Number of Decks: {{user.public_deck_count}} </h5>
            </div>
          {% endif %}
          {% endfor %}
        </div>
      </div>
    {% else %}
      <p>No users matched that search</p>
    {% endif %}
  </div>
  <!-- End User Results -->

  <!-- Deck Results -->
  <div class="deck_search_results">
    <h1>Decks:</h1>
    {% if deck_list %}
      <div class="row mar-b-30">
	      <div class="col-md-12">
          {% for deck in deck_list %}
            <div id={{deck.orig_deck_id}} class="DeckResult">
              <div class="image-caption image-caption-search-result">
                <a href="/cards/study/?deck_id={{deck.orig_deck_id}}" class="deck_result_options label label-info icon" data-toggle="tooltip" data-placement="top" title="Study">
                  <i class="deck_options fa fa-book"></i>
                </a>
                <a href="/cards/view_shared_deck/?deck_id={{ deck.orig_deck_id }}" class="deck_result_options label label-info icon" data-toggle="tooltip" data-placement="top" title="View">
                  <i class="deck_options fa fa-eye"></i>
                </a>
                <a data-toggle="modal" href="#CloneDeck" class="CloneDeck clone-deck-toggle deck_result_options label label-info icon" data-toggle="tooltip" data-placement="top" title="Clone">
                  <i class="deck_options fa fa-copy"></i>
                </a>
              </div>
				      <img class="DeckResult" src="{% cycle '/static/img/StackOfFlashCards.png' '/static/img/StackOfFlashCards2.png' '/static/img/StackOfFlashCards3.png' %}"></img>
				      <h4>{{ deck.deck_name }}</h4>
              <h5>By: {{ deck.username }} </h5>
              <h5>Number of Cards: {{ deck.card_count }} <h5>
            </div>
          {% endfor %}
        </div>
      </div>
    {% else %}
      <p>No public decks matched that search</p>
    {% endif %}
  </div>
  <!-- End Deck Results -->

</div>
<!-- End Search Results Container -->



<!-- Clone Deck Modal -->
<div aria-hidden="true" aria-labelledby="CloneNewDeck" role="dialog" tabindex="-1" id="CloneDeck" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Clone Deck</h4>
      </div>
      <form id="clone-deck-form" method="POST" class="form-signin" action="" style="visibility: visible;">
        {% csrf_token %}
        <div class="modal-body">
          <!-- Check for error messages from bad form data -->
          <p id="clone-deck-error"></p>
          {% for field in clone_form %}
            {% if field.name == "deck_name" %}
              <label for="id_deck_name">Deck Name:</label>
              <input class="form-control" id="id_deck_name" name="{{ field.name}}" type="text">
            {% elif field.name == "share_flag" %}
              <label for="id_share_flag">Share With Others:</label>
              <input id="id_share_flag" name="{{ field.name}}" type="checkbox">
            
              
            {% endif %}
          {% endfor %}
          <!-- original deck id -->
          <input id="clone-deck-id-input" type="hidden" name="clone-deck-id" value="">
          <input id="user-id" class="curr-user" type="hidden" name="curr-user" value="{{ sign }}">
        </div>
        <div class="modal-footer">
          <button id="clone-deck-cancel" data-dismiss="modal" class="btn btn-default" type="button">Cancel</button>
          <button id="clone-deck-submit" class="btn btn-success" type="submit">Clone Deck!</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- End Modal -->

{% endblock %}

slugnotes/study_notes_project/templates/flash_cards/shared_profile.html
{% extends "base.html" %}
{% block content %}
<div class="breadcrumbs">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-sm-4">
                    <h3>{{ shared_user_name }}'s Decks</h3>
                </div>
            </div>
        </div>
    </div>

    <!-- Main Container -->
    <div class="container">
      <div class="row mar-b-30">
        <div class="col-md-12">
          {% for deck in shared_decks reversed %}
          <div id={{deck.orig_deck_id}} class="deck">
            <div class="image-caption">
              <a href="/cards/study/?deck_id={{ deck.orig_deck_id }}" class="deck_options label label-info icon" data-toggle="tooltip" data-placement="top" title="Study">
                <i class="deck_options fa fa-book"></i>
              </a>
              <a href="/cards/view_shared_deck/?deck_id={{ deck.orig_deck_id }}" class="deck_result_options label label-info icon" data-toggle="tooltip" data-placement="top" title="View">
                  <i class="deck_options fa fa-eye"></i>
              </a>
              <a data-toggle="modal" href="#CloneDeck" class="CloneDeck clone-deck-toggle deck_options label label-info icon" data-toggle="tooltip" data-placement="top" title="Clone">
                <i class="deck_options fa fa-copy"></i>
              </a>
            </div>
            <img class="deck" src="{% cycle '/static/img/StackOfFlashCards.png' '/static/img/StackOfFlashCards2.png' '/static/img/StackOfFlashCards3.png' %}"></img>
            <h6 class="deck_name">{{ deck.deck_name }}</h6>
            {% if deck.share %}
            <input class="share-set" type="hidden" name="yes" value="yes">
            {% else %}
            <input class="share-set" type="hidden" name="no" value="no">
            {% endif %}
          </div>
          {% endfor %}
        </div>
      </div>
    </div>


    <!-- End Main Container -->

<!-- Clone Deck Modal -->
<div aria-hidden="true" aria-labelledby="CloneNewDeck" role="dialog" tabindex="-1" id="CloneDeck" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Clone Deck</h4>
      </div>
      <form id="clone-deck-form" method="POST" class="form-signin" action="" style="visibility: visible;">
        {% csrf_token %}
        <div class="modal-body">
          <!-- Check for error messages from bad form data -->
          <p id="clone-deck-error"></p>
          {% for field in clone_form %}
            {% if field.name == "deck_name" %}
              <label for="id_deck_name">Deck Name:</label>
              <input class="form-control" id="id_deck_name" name="{{ field.name}}" type="text">
            {% elif field.name == "share_flag" %}
              <label for="id_share_flag">Share With Others:</label>
              <input id="id_share_flag" name="{{ field.name}}" type="checkbox">
            
              
            {% endif %}
          {% endfor %}
          <!-- original deck id -->
          <input id="clone-deck-id-input" type="hidden" name="clone-deck-id" value="">
          <input id="user-id" class="curr-user" type="hidden" name="curr-user" value="{{ sign }}"
        </div>
        <div class="modal-footer">
          <button id="clone-deck-cancel" data-dismiss="modal" class="btn btn-default" type="button">Cancel</button>
          <button id="clone-deck-submit" class="btn btn-success" type="submit">Clone Deck!</button>
        </div>
      </form>
    </div>
  </div>
</div>
    <!-- End Modal -->

{% endblock %}

slugnotes/study_notes_project/templates/flash_cards/view_shared_deck.html
{% extends "base.html" %}
{% block content %}

<!-- Title -->
<div class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-sm-4">
         <h3>{{ deck_name }} by: {{ username }}</h3>
      </div>
      <div class="col-lg-8 col-sm-8">
        <a href="/cards/study/?deck_id={{ orig_deck_id }}"> 
          <div class="pull-right left-align breadcrumbs-button round-five wow pulse" data-wow-duration="2s" data-wow-delay="1s" data-toggle="tooltip" data-placement="top" title="Study">
            <i class="breadcrumbs-button fa fa-book"></i>
          </div>
        </a>
        <a data-toggle="modal" class="CloneDeck" href="#CloneDeck">
          <div class="pull-right breadcrumbs-button round-five wow pulse" data-wow-duration="2s" data-wow-delay=".6s" data-toggle="tooltip" data-placement="top" title="Clone">
              <i class="fa fa-copy"></i>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>
<!-- End Title -->

<!-- Main Container -->
<div class="container">
  <div class="row mar-b-30">
    <div class="col-md-12">
      {% for card in card_list reversed %}
        <div id={{card.card_id}} class="small_card">
          <div class="small_card_content">
            <p class="card_front">{{card.front}}</p>
            <p class="card_back hidden">{{card.back|linebreaksbr}}</p>
          </div>
          <div class="image-caption image-caption-card">
            <a class="card_options flip_card label label-info icon" data-toggle="tooltip" data-placement="top" title="Flip">
              <i class="deck_options fa fa-undo"></i>
            </a>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>
<!-- End Main Container -->

<!-- Clone Deck Modal -->
<div aria-hidden="true" aria-labelledby="CloneNewDeck" role="dialog" tabindex="-1" id="CloneDeck" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Clone Deck</h4>
      </div>
      <form id="clone-deck-form" method="POST" class="form-signin" action="" style="visibility: visible;">
        {% csrf_token %}
        <div class="modal-body">
          <!-- Check for error messages from bad form data -->
          <p id="clone-deck-error"></p>
          {% for field in clone_form %}
            {% if field.name == "deck_name" %}
              <label for="id_deck_name">Deck Name:</label>
              <input class="form-control" id="id_deck_name" name="{{ field.name}}" type="text">
            {% elif field.name == "share_flag" %}
              <label for="id_share_flag">Share With Others:</label>
              <input id="id_share_flag" name="{{ field.name}}" type="checkbox">
            
              
            {% endif %}
          {% endfor %}
          <!-- original deck id -->
          <input id="clone-deck-id-input" type="hidden" name="clone-deck-id" value="{{ orig_deck_id }}">
          <input id="user-id" class="curr-user" type="hidden" name="curr-user" value="{{ sign }}">
        </div>
        <div class="modal-footer">
          <button id="clone-deck-cancel" data-dismiss="modal" class="btn btn-default" type="button">Cancel</button>
          <button id="clone-deck-submit" class="btn btn-success" type="submit">Clone Deck!</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- End Modal -->

{% endblock %}